// export const busDetails = [
//       {
//         "bus_id": "BUS001",
//         "bus_name": "Delhi Express",
//         "bus_company": "ABC Travels",
//         "origin": "Delhi",
//         "destination": "Mumbai",
//         "arrival_time": "10:00 PM",
//         "departure_time": "06:00 AM",
//         "ticket_price": 1200,
//         "available_seats": 30
//       },
//       {
//         "bus_id": "BUS002",
//         "bus_name": "Mumbai Magic",
//         "bus_company": "XYZ Travels",
//         "origin": "Mumbai",
//         "destination": "Delhi",
//         "arrival_time": "09:00 PM",
//         "departure_time": "05:00 AM",
//         "ticket_price": 1100,
//         "available_seats": 28
//       },
//       {
//         "bus_id": "BUS003",
//         "bus_name": "Bangalore Cruiser",
//         "bus_company": "PQR Travels",
//         "origin": "Bangalore",
//         "destination": "Chennai",
//         "arrival_time": "06:00 PM",
//         "departure_time": "10:00 AM",
//         "ticket_price": 800,
//         "available_seats": 35
//       },
//       {
//         "bus_id": "BUS004",
//         "bus_name": "Chennai Connect",
//         "bus_company": "LMN Travels",
//         "origin": "Chennai",
//         "destination": "Bangalore",
//         "arrival_time": "05:30 PM",
//         "departure_time": "09:30 AM",
//         "ticket_price": 850,
//         "available_seats": 32
//       },
//       {
//         "bus_id": "BUS005",
//         "bus_name": "Kolkata Express",
//         "bus_company": "OPQ Travels",
//         "origin": "Kolkata",
//         "destination": "Delhi",
//         "arrival_time": "08:00 PM",
//         "departure_time": "02:00 PM",
//         "ticket_price": 1500,
//         "available_seats": 25
//       },
//       {
//         "bus_id": "BUS006",
//         "bus_name": "Delhi Voyager",
//         "bus_company": "RST Travels",
//         "origin": "Delhi",
//         "destination": "Kolkata",
//         "arrival_time": "09:00 PM",
//         "departure_time": "03:00 PM",
//         "ticket_price": 1400,
//         "available_seats": 27
//       },
      
      
//     ];
  

 

   export const  busDetails = [
    {
      "bus_id": 1,
      "bus_name": "Nanded Express",
      "origin": "Nanded",
      "destination": "Pune",
      "arrival_time": "08:00 AM",
      "departure_time": "05:00 AM",
      "ticket_price": 500,
      "customer_rating": 4.2,
      "AC": true,
      "pickup_points": ["Nanded Bus Stand", "Nanded Railway Station"],
      "dropoff_points": ["Pune Bus Stand", "Pune Railway Station"],
      "cities_between": ["Parbhani", "Solapur"],
      "available_seats": 30
    },
    {
      "bus_id": 2,
      "bus_name": "Mumbai Local",
      "origin": "Mumbai",
      "destination": "Aurangabad",
      "arrival_time": "12:00 PM",
      "departure_time": "09:00 AM",
      "ticket_price": 700,
      "customer_rating": 4.5,
      "AC": true,
      "pickup_points": ["Mumbai Central", "Borivali"],
      "dropoff_points": ["Aurangabad Bus Stand", "Aurangabad Railway Station"],
      "cities_between": ["Nashik"],
      "available_seats": 25
    },
    {
      "bus_id": 3,
      "bus_name": "Nagpur Luxury",
      "origin": "Nagpur",
      "destination": "Surat",
      "arrival_time": "02:00 PM",
      "departure_time": "10:00 AM",
      "ticket_price": 900,
      "customer_rating": 4.0,
      "AC": true,
      "pickup_points": ["Nagpur Bus Stand", "Nagpur Airport"],
      "dropoff_points": ["Surat Bus Stand", "Surat Railway Station"],
      "cities_between": ["Akola"],
      "available_seats": 40
    },
    {
      "bus_id": 4,
      "bus_name": "Hyderabad Sleeper",
      "origin": "Hyderabad",
      "destination": "Bangalore",
      "arrival_time": "06:00 PM",
      "departure_time": "01:00 PM",
      "ticket_price": 1200,
      "customer_rating": 4.8,
      "AC": true,
      "pickup_points": ["Hyderabad Bus Stand", "Hyderabad Airport"],
      "dropoff_points": ["Bangalore Bus Stand", "Bangalore Railway Station"],
      "cities_between": ["Gulbarga"],
      "available_seats": 20
    },
    {
      "bus_id": 5,
      "bus_name": "Goa Luxury",
      "origin": "Goa",
      "destination": "Indore",
      "arrival_time": "09:00 PM",
      "departure_time": "04:00 PM",
      "ticket_price": 1000,
      "customer_rating": 4.3,
      "AC": true,
      "pickup_points": ["Goa Bus Stand", "Goa Airport"],
      "dropoff_points": ["Indore Bus Stand", "Indore Railway Station"],
      "cities_between": ["Pune", "Mumbai"],
      "available_seats": 35
    },
    {
      "bus_id": 6,
      "bus_name": "Delhi AC",
      "origin": "Delhi",
      "destination": "Ahmedabad",
      "arrival_time": "01:00 AM",
      "departure_time": "08:00 PM",
      "ticket_price": 1500,
      "customer_rating": 4.6,
      "AC": true,
      "pickup_points": ["Delhi Bus Stand", "Delhi Airport"],
      "dropoff_points": ["Ahmedabad Bus Stand", "Ahmedabad Railway Station"],
      "cities_between": ["Jaipur"],
      "available_seats": 45
    },
    {
      "bus_id": 7,
      "bus_name": "Parbhani to Solapur Fast",
      "origin": "Parbhani",
      "destination": "Solapur",
      "arrival_time": "03:00 AM",
      "departure_time": "10:00 PM",
      "ticket_price": 800,
      "customer_rating": 4.1,
      "AC": false,
      "pickup_points": ["Parbhani Bus Stand", "Parbhani Railway Station"],
      "dropoff_points": ["Solapur Bus Stand", "Solapur Railway Station"],
      "cities_between": ["Osmanabad"],
      "available_seats": 50
    },
    {
      "bus_id": 8,
      "bus_name": "Akola to Nashik Express",
      "origin": "Akola",
      "destination": "Nashik",
      "arrival_time": "05:00 AM",
      "departure_time": "12:00 AM",
      "ticket_price": 600,
      "customer_rating": 4.4,
      "AC": false,
      "pickup_points": ["Akola Bus Stand", "Akola Airport"],
      "dropoff_points": ["Nashik Bus Stand", "Nashik Railway Station"],
      "cities_between": ["Amravati", "Dhule"],
      "available_seats": 28
    },
    {
      "bus_id": 9,
      "bus_name": "Ayodhya to Agra Luxury",
      "origin": "Ayodhya",
      "destination": "Agra",
      "arrival_time": "08:00 AM",
      "departure_time": "02:00 AM",
      "ticket_price": 700,
      "customer_rating": 4.7,
      "AC": true,
      "pickup_points": ["Ayodhya Bus Stand", "Ayodhya Railway Station"],
      "dropoff_points": ["Agra Bus Stand", "Agra Airport"],
      "cities_between": ["Kanpur", "Mathura"],
      "available_seats": 10
    },
    {
      "bus_id": 10,
      "bus_name": "Vrindavan to Latur Deluxe",
      "origin": "Vrindavan",
      "destination": "Latur",
      "arrival_time": "11:00 AM",
      "departure_time": "07:00 AM",
      "ticket_price": 800,
      "customer_rating": 4.9,
      "AC": true,
      "pickup_points": ["Vrindavan Bus Stand", "Vrindavan Railway Station"],
      "dropoff_points": ["Latur Bus Stand", "Latur Airport"],
      "cities_between": ["Mathura", "Agra"],
      "available_seats": 15
    },
    {
      "bus_id": 11,
      "bus_name": "Pune Express",
      "origin": "Pune",
      "destination": "Mumbai",
      "arrival_time": "10:00 AM",
      "departure_time": "07:00 AM",
      "ticket_price": 450,
      "customer_rating": 4.4,
      "AC": true,
      "pickup_points": ["Pune Bus Stand", "Pune Railway Station"],
      "dropoff_points": ["Mumbai Central", "Borivali"],
      "cities_between": [],
      "available_seats": 30
    },
    {
      "bus_id": 12,
      "bus_name": "Aurangabad Shuttle",
      "origin": "Aurangabad",
      "destination": "Nagpur",
      "arrival_time": "02:00 PM",
      "departure_time": "10:00 AM",
      "ticket_price": 550,
      "customer_rating": 4.3,
      "AC": true,
      "pickup_points": ["Aurangabad Bus Stand", "Aurangabad Railway Station"],
      "dropoff_points": ["Nagpur Bus Stand", "Nagpur Airport"],
      "cities_between": [],
      "available_seats": 40
    },
    {
      "bus_id": 13,
      "bus_name": "Surat Superfast",
      "origin": "Surat",
      "destination": "Hyderabad",
      "arrival_time": "07:00 PM",
      "departure_time": "03:00 PM",
      "ticket_price": 750,
      "customer_rating": 4.2,
      "AC": true,
      "pickup_points": ["Surat Bus Stand", "Surat Railway Station"],
      "dropoff_points": ["Hyderabad Bus Stand", "Hyderabad Airport"],
      "cities_between": ["Pune", "Mumbai"],
      "available_seats": 20
    },
    {
      "bus_id": 14,
      "bus_name": "Bangalore Deluxe",
      "origin": "Bangalore",
      "destination": "Goa",
      "arrival_time": "12:00 AM",
      "departure_time": "06:00 PM",
      "ticket_price": 850,
      "customer_rating": 4.8,
      "AC": true,
      "pickup_points": ["Bangalore Bus Stand", "Bangalore Railway Station"],
      "dropoff_points": ["Goa Bus Stand", "Goa Airport"],
      "cities_between": ["Hubli"],
      "available_seats": 25
    },
    {
      "bus_id": 15,
      "bus_name": "Indore Express",
      "origin": "Indore",
      "destination": "Delhi",
      "arrival_time": "05:00 AM",
      "departure_time": "12:00 AM",
      "ticket_price": 900,
      "customer_rating": 4.5,
      "AC": true,
      "pickup_points": ["Indore Bus Stand", "Indore Railway Station"],
      "dropoff_points": ["Delhi Bus Stand", "Delhi Airport"],
      "cities_between": ["Bhopal", "Jaipur"],
      "available_seats": 10
    },
    {
      "bus_id": 16,
      "bus_name": "Ahmedabad Sleeper",
      "origin": "Ahmedabad",
      "destination": "Parbhani",
      "arrival_time": "10:00 AM",
      "departure_time": "06:00 AM",
      "ticket_price": 650,
      "customer_rating": 4.1,
      "AC": false,
      "pickup_points": ["Ahmedabad Bus Stand", "Ahmedabad Railway Station"],
      "dropoff_points": ["Parbhani Bus Stand", "Parbhani Railway Station"],
      "cities_between": ["Mumbai", "Pune"],
      "available_seats": 35
    },
    {
      "bus_id": 17,
      "bus_name": "Solapur Fast",
      "origin": "Solapur",
      "destination": "Akola",
      "arrival_time": "02:00 PM",
      "departure_time": "10:00 AM",
      "ticket_price": 700,
      "customer_rating": 4.6,
      "AC": false,
      "pickup_points": ["Solapur Bus Stand", "Solapur Railway Station"],
      "dropoff_points": ["Akola Bus Stand", "Akola Airport"],
      "cities_between": ["Osmanabad"],
      "available_seats": 45
    },
    {
      "bus_id": 18,
      "bus_name": "Nashik Express",
      "origin": "Nashik",
      "destination": "Ayodhya",
      "arrival_time": "06:00 PM",
      "departure_time": "01:00 PM",
      "ticket_price": 800,
      "customer_rating": 4.3,
      "AC": true,
      "pickup_points": ["Nashik Bus Stand", "Nashik Railway Station"],
      "dropoff_points": ["Ayodhya Bus Stand", "Ayodhya Railway Station"],
      "cities_between": ["Aurangabad"],
      "available_seats": 15
    },
    {
      "bus_id": 19,
      "bus_name": "Agra Luxury",
      "origin": "Agra",
      "destination": "Vrindavan",
      "arrival_time": "09:00 PM",
      "departure_time": "04:00 PM",
      "ticket_price": 950,
      "customer_rating": 4.7,
      "AC": true,
      "pickup_points": ["Agra Bus Stand", "Agra Airport"],
      "dropoff_points": ["Vrindavan Bus Stand", "Vrindavan Railway Station"],
      "cities_between": ["Mathura"],
      "available_seats": 20
    },
    {
      "bus_id": 20,
      "bus_name": "Latur Deluxe",
      "origin": "Latur",
      "destination": "Nanded",
      "arrival_time": "01:00 AM",
      "departure_time": "08:00 PM",
      "ticket_price": 850,
      "customer_rating": 4.9,
      "AC": true,
      "pickup_points": ["Latur Bus Stand", "Latur Airport"],
      "dropoff_points": ["Nanded Bus Stand", "Nanded Railway Station"],
      "cities_between": [],
      "available_seats": 25
    }
    
  ]

